category_meta not working due to missing date
This commit shows the category_meta plugin completely failing. If you go
to `category/category.html` in the generated site you will see
"Category:" followed by nothing. In the template, `category.html`
specifies `{{ category.description }}` to be there.

Looking at the output of `make html` we can see the issue:

ERROR: Skipping category/index.md: could not find information about
  'date'
ERROR: No category assignment for ~/pelican_category_meta_problems/
  content/category/post.md (~/pelican_category_meta_problems/content
  /category/post.md)

`category/index.md` is missing the `Date` metadata. This is neither
specified by the documentation of category_meta nor does it really make
sense. I suspect at one point Pelican did not require articles it reads
to have dates.